# version: "3.9"
services:
  admin-mock:
    image: stoplight/prism
    container_name: admin-mock
    command: mock -h 0.0.0.0 -p 4010 /tmp/admin/openapi.yml
    volumes:
      - ./docs:/tmp
  admin-agent-mock:
    image: stoplight/prism
    container_name: admin-agent-mock
    command: mock -h 0.0.0.0 -p 4010 /tmp/admin-agent/openapi.yml
    volumes:
      - ./docs:/tmp
  order-mock:
    image: stoplight/prism
    container_name: order-mock
    command: mock -h 0.0.0.0 -p 4010 /tmp/order/openapi.yml
    volumes:
      - ./docs:/tmp
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    environment:
      - SWAGGER_JSON=/openapi/admin-openapi.yml
    volumes:
      - ./docs/admin/openapi.yml:/openapi/admin-openapi.yml
      - ./docs/admin-agent/openapi.yml:/openapi/admin-agent-openapi.yml
      - ./docs/order/openapi.yml:/openapi/order-openapi.yml
    ports:
      - "3030:8080"
  proxy:
    image: caddy
    container_name: proxy-caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "8180:80"
    depends_on:
      - admin-mock
      - admin-agent-mock
      - order-mock
