version: "3.9"
services:
  admin-mock:
    image: stoplight/prism
    container_name: admin-mock
    command: mock -h 0.0.0.0 /tmp/admin/openapi.yml
    volumes:
      - ./docs:/tmp
    ports:
      - "4010:4010"
  admin-agent-mock:
    image: stoplight/prism
    container_name: admin-agent-mock
    command: mock -h 0.0.0.0 /tmp/admin-admin-agent/openapi.yml
    volumes:
      - ./docs:/tmp
    ports:
      - "4011:4010"
  order-mock:
    image: stoplight/prism
    container_name: order-mock
    command: mock -h 0.0.0.0 /tmp/order/openapi.yml
    volumes:
      - ./docs:/tmp
    ports:
      - "4012:4010"
  admin-doc:
    image: redocly/redoc
    container_name: admin-doc
    environment:
      - SPEC_URL=swagger.yml
    volumes:
      - ./docs/admin/openapi.yml:/usr/share/nginx/html/swagger.yml
    ports:
      - "3030:80"
  admin-agent-doc:
    image: redocly/redoc
    container_name: admin-agent-doc
    environment:
      - SPEC_URL=swagger.yml
    volumes:
      - ./docs/admin-agent/openapi.yml:/usr/share/nginx/html/swagger.yml
    ports:
      - "3031:80"
  order-doc:
    image: redocly/redoc
    container_name: order-doc
    environment:
      - SPEC_URL=swagger.yml
    volumes:
      - ./docs/order/openapi.yml:/usr/share/nginx/html/swagger.yml
    ports:
      - "3032:80"
