openapi: "3.0.3"
info:
  title: API Hands_on
  version: "1.0"
  license:
    name: kazuki_ito

components:
  securitySchemes:
    BeareAuth:
      type: http
      scheme: bearer
servers:
  - url: http://localhost:8000/api
    description: 8001のAPIサーバー
  - url: http://localhost:8001/api
    description: 8001のAPIサーバー
  - url: http://localhost:8002/api
    description: 8001のAPIサーバー
  - url: http://localhost:8003/api
    description: 8001のAPIサーバー
paths:
  /health-check:
    get:
      summary: test for first api specification
      security: []
      responses:
        "200":
          description: OK
