openapi: "3.0.3"
info:
  title: B-Dash2 API
  version: "1.0"
  description: hands_on for openapi of B-Dash2
  license:
    name: kazuki_ito
    url: https://gonzuiswimmer.github.io/swagger_hands_on/admin/

tags:
  - name: healthCheck
    description: 動作確認用API
  - name: auth
    description: 認証系API
  - name: user
    description: 一般ユーザー系API
  - name: top
    description: top画面系API
  - name: department
    description: 部署系API
  - name: adminUser
    description: 管理者向けユーザー制御系API
  - name: adminUserAnnouncement
    description: 管理者向けお知らせ系API
  - name: adnimuserInquiry
    description: 管理者向け問い合わせ系API
  - name: adminUserRole
    description: 管理者向けロール制御系API

servers:
  - url: http://localhost:{port}/api
    description: local環境のAPIサーバー。cf.8180はモックサーバー(=プロキシサーバー)
    variables:
      port:
        default: "80"
        enum: ["80", "8180/admin-mock"]
  - url: https://xxx-admin/api
    description: 開発環境のAPIサーバー

paths:
  /health-check:
    $ref: ./paths/health-check.yml
  /auth/login:
    $ref: ./paths/auth.yml#/login
  /auth/logout:
    $ref: ./paths/auth.yml#/logout
  /user:
    $ref: ./paths/user.yml
  /top:
    $ref: ./paths/top.yml
  /getDepartments:
    $ref: ./paths/getDepartments.yml
  /admin/users:
    $ref: ./paths/admin/users/index.yml
  /admin/users/store:
    $ref: ./paths/admin/users/store.yml
  /admin/users/edit/{id}:
    $ref: ./paths/admin/users/edit.yml
  /admin/users/update/{id}:
    $ref: ./paths/admin/users/update.yml
  /admin/users/destroy/{id}:
    $ref: ./paths/admin/users/destroy.yml
  /admin/users/roles:
    $ref: ./paths/admin/users/roles.yml
  /admin/users/roles/new/{id}:
    $ref: ./paths/admin/users/rolesNew.yml
  /admin/users/roles/delete/{id}:
    $ref: ./paths/admin/users/rolesDelete.yml

components:
  securitySchemes:
    BeareAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
