openapi: "3.0.3"
info:
  title: B-Dash2 API
  version: "1.0"
  description: hands_on for openapi of B-Dash2
  license:
    name: kazuki_ito
    url: https://gonzuiswimmer.github.io/swagger_hands_on/admin/

components:
  securitySchemes:
    BeareAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

tags:
  - name: health-check
    description: 動作確認用API
  - name: admin-users
    description: 管理/ユーザー系API
  - name: admin-announcement
    description: 管理/お知らせ系API
  - name: admin-inquiry
    description: 管理/問い合わせ系API

servers:
  - url: http://localhost:{port}/api
    description: local環境のAPIサーバー。cf.8180はモックサーバー(=プロキシサーバー)
    variables:
      port:
        default: "80"
        enum: ["80", "8180/admin-mock"]
  - url: https://xxx-admin/api
    description: 開発環境のAPIサーバー

paths:
  /health-check:
    get:
      summary: test for first api specification
      security: []
      tags:
        - health-check
      responses:
        "200":
          description: OK
        "400":
          description: "Error"
  /user:
    $ref: ./paths/user.yml
  /top:
    $ref: ./paths/top.yml
  /getDepartments:
    $ref: ./paths/getDepartments.yml
  /admin/users:
    $ref: ./paths/admin/users/index.yml
  /admin/users/store:
    $ref: ./paths/admin/users/store.yml
  /admin/users/edit/{id}:
    $ref: ./paths/admin/users/edit.yml
  /admin/users/update/{id}:
    $ref: ./paths/admin/users/update.yml
  /admin/users/destroy/{id}:
    $ref: ./paths/admin/users/destroy.yml
  /admin/users/roles:
    $ref: ./paths/admin/users/roles.yml
  /admin/users/roles/new/{id}:
    $ref: ./paths/admin/users/rolesNew.yml
  /admin/users/roles/delete/{id}:
    $ref: ./paths/admin/users/rolesDelete.yml
