name: Deploy OpenAPI Docs

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: build root.yml
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Lint
      - name: Redocly Lint Order
        uses: fluximus-prime/redocly-cli-github-action@v1
        with:
          args: "lint ./openapi/order/root.yml --format github-actions"
      - name: Redocly Lint Admin
        uses: fluximus-prime/redocly-cli-github-action@v1
        with:
          args: "lint ./openapi/admin/root.yml --format github-actions"
      - name: Redocly Lint Admin Agent
        uses: fluximus-prime/redocly-cli-github-action@v1
        with:
          args: "lint ./openapi/admin-agent/root.yml --format github-actions"

      # Build
      - name: Redocly Build Order
        uses: fluximus-prime/redocly-cli-github-action@v1
        with:
          args: "build-docs ./openapi/order/root.yml --output=./docs/order/index.html"
      - name: Redocly Build Admin
        uses: fluximus-prime/redocly-cli-github-action@v1
        with:
          args: "build-docs ./openapi/admin/root.yml --output=./docs/admin/index.html"

      # Bundle
      - name: Redocly Build Admin Agent
        uses: fluximus-prime/redocly-cli-github-action@v1
        with:
          args: "build-docs ./openapi/admin-agent/root.yml --output=./docs/admin-agent/index.html"
      - name: Redocly Bundle Order
        uses: fluximus-prime/redocly-cli-github-action@v1
        with:
          args: bundle ./openapi/order/root.yml --output=./docs/order/openapi.yml
      - name: Redocly Bundle Admin
        uses: fluximus-prime/redocly-cli-github-action@v1
        with:
          args: bundle ./openapi/admin/root.yml --output=./docs/admin/openapi.yml
      - name: Redocly Bundle Admin Agent
        uses: fluximus-prime/redocly-cli-github-action@v1
        with:
          args: bundle ./openapi/admin-agent/root.yml --output=./docs/admin-agent/openapi.yml

      # Github Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
