name: Deploy OpenAPI Docs

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: build root.yml
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Redocly Lint
        uses: fluximus-prime/redocly-cli-github-action@v1
        with:
          args: "lint ./openapi/order/root.yml --format github-actions && lint ./openapi/admin/root.yml --format github-actions && lint ./openapi/admin-agent/root.yml --format github-actions"
          # args: >
          #   lint ./openapi/order/root.yml --format github-actions
          #   lint ./openapi/admin/root.yml --format github-actions
          #   lint ./openapi/admin-agent/root.yml --format github-actions
      - name: Redocly Build
        uses: fluximus-prime/redocly-cli-github-action@v1
        with:
          args: "build-docs ./openapi/order/root.yml --output=./docs/order/index.html && build-docs ./openapi/admin/root.yml --output=./docs/admin/index.html && build-docs ./openapi/admin-agent/root.yml --output=./docs/admin-agent/index.html"
          # args: >
          #   build-docs ./openapi/order/root.yml --output=./docs/order/index.html
          #   build-docs ./openapi/admin/root.yml --output=./docs/admin/index.html
          #   build-docs ./openapi/admin-agent/root.yml --output=./docs/admin-agent/index.html
      - name: Redocly Bundle
        uses: fluximus-prime/redocly-cli-github-action@v1
        with:
          args: bundle ./openapi/order/root.yml --output=./docs/order/openapi.yml && bundle ./openapi/admin/root.yml --output=./docs/admin/openapi.yml && bundle ./openapi/admin-agent/root.yml --output=./docs/admin-agent/openapi.yml
          # args: >
          #   bundle ./openapi/order/root.yml --output=./docs/order/openapi.yml
          #   bundle ./openapi/admin/root.yml --output=./docs/admin/openapi.yml
          #   bundle ./openapi/admin-agent/root.yml --output=./docs/admin-agent/openapi.yml
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
